# Generated by Django 3.2.4 on 2021-06-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210615_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45)),
                ('nickname', models.CharField(max_length=50)),
                ('cotent', models.TextField(blank=True)),
                ('room_title', models.CharField(max_length=45)),
                ('room_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
