# Generated by Django 3.2.4 on 2021-06-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_numbers_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='TW_2330',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=500)),
            ],
        ),
    ]
