# Generated by Django 3.2.4 on 2021-06-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Numbers_room',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Room_detail',
        ),
        migrations.DeleteModel(
            name='TW_2330',
        ),
    ]
