# Generated by Django 3.2.4 on 2021-06-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20210623_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='food',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='numbers',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Numbers_room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Room_detail',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Numbers',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
