# Generated by Django 3.2.4 on 2021-06-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20210623_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Stock_code',
        ),
        migrations.RenameField(
            model_name='user_login',
            old_name='password',
            new_name='Stock_code',
        ),
        migrations.RemoveField(
            model_name='user_login',
            name='login_check',
        ),
    ]
