# Generated by Django 3.2.4 on 2021-06-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_remove_user_login_login_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='Stock_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='user_login',
            old_name='nickname',
            new_name='Stock_code',
        ),
        migrations.RenameField(
            model_name='user_login',
            old_name='password',
            new_name='content',
        ),
    ]
