# Generated by Django 3.2.4 on 2021-06-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_auto_20210623_0213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_login',
        ),
    ]
